// File generated by FlutterFire CLI.
// ignore_for_file: type=lint 
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLLZxqRcMTnom5MJ65ZsZlZrW9wTV3mkA',
    appId: '1:528810179327:web:5e36a4528d522e782c2aca',
    messagingSenderId: '528810179327',
    projectId: 'chat-app-b143f',
    authDomain: 'chat-app-b143f.firebaseapp.com',
    storageBucket: 'chat-app-b143f.appspot.com',
    measurementId: 'G-Y12GM7K0J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3BmLp-fd3DP81NQy4rXwHbczzjZSlMJo',
    appId: '1:528810179327:android:2365ea9deacd8af02c2aca',
    messagingSenderId: '528810179327',
    projectId: 'chat-app-b143f',
    storageBucket: 'chat-app-b143f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0dty5bwcv6s61-DvovYFcnA9DMD6lT8I',
    appId: '1:528810179327:ios:960875501ee2870a2c2aca',
    messagingSenderId: '528810179327',
    projectId: 'chat-app-b143f',
    storageBucket: 'chat-app-b143f.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0dty5bwcv6s61-DvovYFcnA9DMD6lT8I',
    appId: '1:528810179327:ios:960875501ee2870a2c2aca',
    messagingSenderId: '528810179327',
    projectId: 'chat-app-b143f',
    storageBucket: 'chat-app-b143f.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLLZxqRcMTnom5MJ65ZsZlZrW9wTV3mkA',
    appId: '1:528810179327:web:ee973cfd8fb4ff0e2c2aca',
    messagingSenderId: '528810179327',
    projectId: 'chat-app-b143f',
    authDomain: 'chat-app-b143f.firebaseapp.com',
    storageBucket: 'chat-app-b143f.appspot.com',
    measurementId: 'G-YTDVGLKEQT',
  );
}
